[project]
name = "project-manager"
version = "0.1.0"
description = "An agentic AI project manager platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[anthropic]>=0.3.25",
    "langgraph>=0.4.7",
]
