[project]
name = "project-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=0.3.3",
    "langgraph>=0.6.2",
    "ollama>=0.4.9",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
]
